spring.application.name=voltpay-backend
server.port=8080
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://nandanibhati2005_db_user:kquWp5GzRJzyTEgO@cluster0.r2fgrct.mongodb.net/voltpay?retryWrites=true&w=majority&appName=Cluster0}
firebase.credentials.path=${FIREBASE_CREDENTIALS_PATH:firebase-credentials.json}

spring.jackson.serialization.write-dates-as-timestamps=true
