spring.application.name=voltpay-backend
server.port=8080
spring.data.mongodb.uri=${MONGODB_URI}
firebase.credentials.path=${FIREBASE_CREDENTIALS_PATH:firebase-credentials.json}

spring.jackson.serialization.write-dates-as-timestamps=true
